### ISSUE TITLE
Plugin 'require' attribute does nothing

### ISSUE THREAD

**Issue by WiggleWizard** [Zinglish/alice#5]
The 'require' should tell the plugin manager that the plugins in the 'require' array should be loaded before the plugin. This should either stop Alice and tell the moderator to enable/install the required plugin(s) or automatically attempt to load it and if not found then stop Alice and inform the moderator to install it.

**Comment by dschoerk** [comment]
1. all plugins are loaded in arbitrary order
2. plugins are prioritized
3. all plugins are initialized such that required plugins are initialized first, if a plugin is not available an error is printed to stdout
