### ISSUE TITLE
!kick

### ISSUE THREAD

**Issue by WiggleWizard** [Zinglish/alice#7]
Plugin should have custom kick message too. I believe WonderlandX doesn't have a function to call to kick a player but once it does I will reference the push in the comments and this plugin can be completed.

**Comment by WiggleWizard** [comment]
Added kick function to WonderlandX( https://github.com/Zinglish/wonderlandx/commit/c7122795aae614f89c896ef4668446d011a68d41). I also added a kick function to Alice's player object (https://github.com/Zinglish/alice/commit/c08cdc57f8abec1b5fe3904dc4430d0ecb438feb): `Player.kick(reason)`

**Comment by dschoerk** [comment]
kick by id and names done
